import 'package:flutter/material.dart';

class CategoryIcons {
  // ✅ أيقونات التصنيفات الرئيسية
  static IconData getIcon(String name) {
    const Map<String, IconData> iconMap = {
      'أجهزة سلامة': Icons.security_rounded,
      'أجهزة كهربائية': Icons.electrical_services_rounded,
      'أزياء الرجل': Icons.man_rounded,
      'ألعاب رقمية': Icons.sports_esports_rounded,
      'إلكترونيات': Icons.devices_rounded,
      'الحديقة': Icons.yard_rounded,
      'الحيوانات': Icons.pets_rounded,
      'الرحلات': Icons.terrain_rounded,
      'السفر': Icons.flight_takeoff_rounded,
      'السيارات': Icons.directions_car_filled_rounded,
      'القهوه': Icons.local_cafe_rounded,
      'الكتب والقرطاسية': Icons.menu_book_rounded,
      'المطبخ والضيافة': Icons.soup_kitchen_rounded,
      'المنزل': Icons.home_rounded,
      'الهدايا': Icons.redeem_rounded,
      'حرف يدوية': Icons.brush_rounded,
      'عالم الطفل': Icons.child_care_rounded,
      'عناية الرجل': Icons.face_rounded,
      'عناية الشخصية': Icons.spa_rounded,
      'عناية المرأة': Icons.face_retouching_natural_rounded,
      'مكملات غذائية': Icons.medication_liquid_rounded,
      'ملحقات رقمية': Icons.cable_rounded,
      'عروض طبية': Icons.medical_services_rounded,
      'منظفات منزلية': Icons.cleaning_services_rounded,
      'مواليد': Icons.child_friendly_rounded,
    };
    return iconMap[name] ?? Icons.grid_view_rounded;
  }

// ✅ أضف دالة منفصلة:
  static String? getImage(String name) {
    const Map<String, String> imageMap = {
      'أجهزة رياضية': 'assets/images/sports_equipment.png',
      'سير كهربائي': 'assets/images/treadmill.png',
      'أزياء المرأة': 'assets/images/ladiesfashion.png',
      'أزياء الرجل': 'assets/images/menfashion.png',
    };
    return imageMap[name];
  }

  // ✅ أيقونات التصنيفات الفرعية — إذا ما وجد يرجع أيقونة الرئيسي
  static IconData getSubIcon(String subName, String parentName) {
    const Map<String, IconData> subIconMap = {
      // أثاث ومنزل
      'أثاث غرف': Icons.bed_rounded,
      'خزائن ملابس': Icons.door_sliding_rounded,
      'كنب ومجالس': Icons.weekend_rounded,
      'رفوف ومكتبات': Icons.shelves,
      'طاولات وكراسي': Icons.table_restaurant_rounded,
      'طاولات تلفزيون': Icons.tv_rounded,
      'فراش نوم': Icons.bed_rounded,
      'مراتب طبية': Icons.bed_rounded,
      'مهادات وبطانيات': Icons.king_bed_rounded,
      'شراشف وبياضات': Icons.layers_rounded,
      'ستائر منزلية': Icons.blinds_rounded,
      'سجاد وموكيت': Icons.layers_rounded,
      'ديكورات الحائط': Icons.wallpaper_rounded,
      'لوحات فنية': Icons.image_rounded,
      'تحف وفازات': Icons.emoji_nature_rounded,
      'تحف تذكارية': Icons.emoji_events_rounded,
      'أرضيات خارجية': Icons.grass_rounded,
      'عشب صناعي': Icons.grass_rounded,
      'مسابح منزلية': Icons.pool_rounded,
      'نوافير وشلالات': Icons.water_rounded,
      'مفارش وأسرة': Icons.bed_rounded,
      'مفارش طاولات': Icons.table_bar_rounded,
      'ديكورات حدائق': Icons.park_rounded,
      'ديكورات وفنون': Icons.palette_rounded,
      'جلسات خارجية': Icons.deck_rounded,
      'كراسي خارجية': Icons.chair_rounded,
      'طاولات خارجية': Icons.table_restaurant_rounded,
      'مداخل وممرات': Icons.door_front_door_rounded,
      'انتركوم منزلي': Icons.doorbell_rounded,
      'بارات حديد': Icons.hardware_rounded,
      'معطرات جو': Icons.air_rounded,
      'منقيات الهواء': Icons.air_rounded,

      // مطبخ وضيافة
      'أدوات تقطيع': Icons.kitchen_rounded,
      'أدوات خبز': Icons.bakery_dining_rounded,
      'أفران غاز': Icons.local_fire_department_rounded,
      'أفران كهرباء': Icons.microwave_rounded,
      'افرام بلت ان': Icons.kitchen_rounded,
      'خلاطات وعجانات': Icons.blender_rounded,
      'قدور ضغط': Icons.set_meal_rounded,
      'قدور وأواني': Icons.set_meal_rounded,
      'قلايات هوائية': Icons.air_rounded,
      'مايكرويفات': Icons.microwave_rounded,
      'محضرات طعام': Icons.blender_rounded,
      'مطاحن كهربائية': Icons.settings_rounded,
      'سكاكين وملاعق': Icons.restaurant_rounded,
      'أواني ضيافة': Icons.emoji_food_beverage_rounded,
      'أطقم تقديم': Icons.restaurant_rounded,
      'أطقم إستقبال': Icons.restaurant_rounded,
      'فناجيل واكواب': Icons.coffee_rounded,
      'أكواب حافظة': Icons.local_cafe_rounded,
      'أكواب سيراميك': Icons.coffee_rounded,
      'لانش بوكس': Icons.lunch_dining_rounded,
      'منظمات المطبخ': Icons.kitchen_rounded,
      'اكسسوارات سفرة': Icons.table_restaurant_rounded,
      'ثلاجات وفريزر': Icons.kitchen_rounded,
      'برادات مياة': Icons.water_drop_rounded,
      'خزانات مياة': Icons.water_rounded,
      'خزانات مياه': Icons.water_rounded,
      'فلاتر مياة': Icons.filter_alt_rounded,
      'فلاتر ورقية': Icons.filter_alt_rounded,
      'غلايات ذكية': Icons.coffee_maker_rounded,
      'ترامس وغلايات': Icons.coffee_maker_rounded,
      'غسالات مواعين': Icons.cleaning_services_rounded,
      'غسيل صحون': Icons.cleaning_services_rounded,
      'مستلزمات شواء': Icons.outdoor_grill_rounded,
      'مواقد خارجية': Icons.outdoor_grill_rounded,
      'مواقد رحلات': Icons.outdoor_grill_rounded,
      'قوالب حلى': Icons.cake_rounded,
      'نكهات وسيرب': Icons.icecream_rounded,
      'سناكات صحية': Icons.food_bank_rounded,
      'مشروبات صحية': Icons.local_drink_rounded,

      // قهوة
      'قهوة سعودية': Icons.local_cafe_rounded,
      'قهوة مختصة': Icons.coffee_rounded,
      'كبسولات قهوة': Icons.coffee_rounded,
      'مكائن اسبريسو': Icons.coffee_maker_rounded,
      'مطاحن قهوة': Icons.settings_rounded,
      'اباريق ترشيح': Icons.local_cafe_rounded,
      'أدوات الباريستا': Icons.coffee_rounded,
      'دلال وأباريق': Icons.local_cafe_rounded,
      'ركن القهوة': Icons.coffee_rounded,

      // إلكترونيات
      'جوالات': Icons.smartphone_rounded,
      'لابتوب': Icons.laptop_rounded,
      'تابلت': Icons.tablet_rounded,
      'تلفزيونات وشاشات': Icons.tv_rounded,
      'بروجكترات': Icons.connected_tv_rounded,
      'سماعات بلوتوث': Icons.headphones_rounded,
      'سماعات ومكبرات': Icons.speaker_rounded,
      'ساعات ذكية': Icons.watch_rounded,
      'ساعات رجالية': Icons.watch_rounded,
      'طابعات وماسحات': Icons.print_rounded,
      'أجهزة مكتبية': Icons.computer_rounded,
      'كاميرات تصوير': Icons.camera_alt_rounded,
      'أدوات التصوير': Icons.camera_rounded,
      'كاميرات مراقبة': Icons.videocam_rounded,
      'شواحن وكوابل': Icons.cable_rounded,
      'شواحن ومحولات': Icons.electrical_services_rounded,
      'توصيلات ومحولات': Icons.electrical_services_rounded,
      'وسائط تخزين': Icons.storage_rounded,
      'بطاقات شحن': Icons.credit_card_rounded,
      'اشتراكات': Icons.subscriptions_rounded,
      'أدوات ستريم': Icons.live_tv_rounded,
      'الواح الطاقة': Icons.solar_power_rounded,

      // ملحقات رقمية
      'اكسسوارات الكمبيوتر': Icons.mouse_rounded,
      'ملحقات الألعاب': Icons.sports_esports_rounded,
      'منضمات ألعاب': Icons.gamepad_rounded,
      'كفرات حماية': Icons.phone_android_rounded,
      'راوتر وشبكات': Icons.router_rounded,
      'أجهزة انترنت': Icons.wifi_rounded,

      // ألعاب رقمية
      'ألعاب إلكترونية': Icons.sports_esports_rounded,
      'ألعاب اكس بوكس': Icons.sports_esports_rounded,
      'العاب بلايستيشن': Icons.sports_esports_rounded,
      'العاب كمبيوتر': Icons.computer_rounded,
      'بلايستيشن واكس بوكس': Icons.sports_esports_rounded,
      'عملات افتراضية': Icons.currency_bitcoin_rounded,

      // ألعاب أطفال
      'ألعاب حركية': Icons.directions_run_rounded,
      'ألعاب خارجية': Icons.park_rounded,
      'ألعاب ذكاء': Icons.psychology_rounded,
      'ألعاب مواليد': Icons.toys_rounded,

      // أزياء رجال
      'بدل رسمية': Icons.dry_cleaning_rounded,
      'بلايز وقمصان': Icons.checkroom_rounded,
      'أشمغة وغتر': Icons.checkroom_rounded,
      'ملابس رياضية': Icons.sports_rounded,
      'ملابس كاجوال': Icons.checkroom_rounded,
      'ملابس شتوية': Icons.ac_unit_rounded,
      'ملابس داخلية': Icons.checkroom_rounded,
      'ملابس نوم': Icons.bedtime_rounded,
      'أحذية رسمية': Icons.checkroom_rounded,
      'أحذية رياضية': Icons.directions_run_rounded,
      'صنادل ونعال': Icons.checkroom_rounded,
      'محافظ واحزمة': Icons.account_balance_wallet_rounded,
      'اكسسوارات وحقائب': Icons.luggage_rounded,
      'عطور الرجل': Icons.water_drop_rounded,

      // أزياء نساء
      'فساتين سهرة': Icons.checkroom_rounded,
      'فساتين يومية': Icons.checkroom_rounded,
      'عبايات وطرح': Icons.checkroom_rounded,
      'تنانير وبناطيل': Icons.checkroom_rounded,
      'كاجوال نسائية': Icons.checkroom_rounded,
      'ملابس رياضيه نسائية': Icons.sports_rounded,
      'ملابس شتويه نسائية': Icons.ac_unit_rounded,
      'ملابس داخلية نسائية': Icons.checkroom_rounded,
      'ملابس نوم نسائية': Icons.bedtime_rounded,
      'جلابيات وقفاطين': Icons.checkroom_rounded,
      'أحذية رسمية نسائية': Icons.checkroom_rounded,
      'أحذية كاجوال نسائية': Icons.checkroom_rounded,
      'مجوهرات وساعات نسائية': Icons.diamond_rounded,
      'خرز ومجوهرات': Icons.diamond_rounded,
      'حقائب يد': Icons.work_rounded,
      'شعر المرأة': Icons.face_retouching_natural_rounded,
      'رموش وحواجب': Icons.face_retouching_natural_rounded,

      // عناية المرأة
      'مكياج عيون': Icons.remove_red_eye_rounded,
      'مكياج وجه': Icons.face_retouching_natural_rounded,
      'عدسات تجميلية': Icons.lens_rounded,
      'ماسكات وجه': Icons.face_retouching_natural_rounded,
      'سيروم بشرة': Icons.water_drop_rounded,
      'ترطيب وجه': Icons.water_drop_rounded,
      'تفتيح بشرة': Icons.wb_sunny_rounded,
      'طلاء اظافر': Icons.brush_rounded,
      'لوشن معطر': Icons.spa_rounded,
      'مرطبات جسم': Icons.spa_rounded,
      'بودرة جسم': Icons.spa_rounded,
      'زيوت طبيعية': Icons.water_drop_rounded,
      'زيوت شعر': Icons.water_drop_rounded,
      'صبغات شعر': Icons.color_lens_rounded,
      'استشوار وفير': Icons.air_rounded,

      // عناية الرجل
      'أدوات حلاقة': Icons.content_cut_rounded,
      'مكائن حلاقة': Icons.content_cut_rounded,
      'عناية باللحية': Icons.face_rounded,
      'صبغات شعر رجاليه': Icons.color_lens_rounded,
      'عناية شعر الرجل': Icons.face_rounded,
      'كريمات وجه الرجل': Icons.face_rounded,
      'عناية جسم الرجل': Icons.spa_rounded,

      // عناية شخصية
      'أدوات استحمام': Icons.shower_rounded,
      'عناية بالفم': Icons.cleaning_services_rounded,
      'مستلزمات اسنان': Icons.cleaning_services_rounded,
      'عناية باليدين': Icons.back_hand_rounded,
      'عناية بالقدمين': Icons.directions_walk_rounded,

      // رياضة
      'أجهزة اوربتراك': Icons.fitness_center_rounded,
      'أجهزة تجديف': Icons.rowing_rounded,
      'أجهزة مساج': Icons.self_improvement_rounded,
      'أجهزة تدليك': Icons.self_improvement_rounded,
      'دامبلز وأوزان': Icons.fitness_center_rounded,
      'دراجات ثابتة': Icons.pedal_bike_rounded,
      'دراجات وسكوترات': Icons.electric_scooter_rounded,
      'سير كهربائي': Icons.directions_run_rounded,
      'مقاعد تمارين': Icons.fitness_center_rounded,
      'أرضيات رياضية': Icons.sports_rounded,
      // سلامة
      'أحذية السلامة': Icons.security_rounded,
      'خوذة وكمامات': Icons.health_and_safety_rounded,
      'سترات عاكسة': Icons.visibility_rounded,
      'أنظمة انذار': Icons.notifications_active_rounded,
      'كاشفات الدخان': Icons.smoke_free_rounded,
      'طفايات حريق': Icons.fire_extinguisher_rounded,
      'كمامات ومعقمات': Icons.masks_rounded,
      'إسعافات أولية': Icons.medical_services_rounded,
      'حقائب إسعاف': Icons.medical_services_rounded,
      'أقفال ذكية': Icons.lock_rounded,
      'أقفال حقائب': Icons.lock_rounded,

      // كهربائية
      'مكيفات سبليت': Icons.ac_unit_rounded,
      'مكيفات شباك': Icons.ac_unit_rounded,
      'مكيفات صحراوية': Icons.ac_unit_rounded,
      'غسالات ونشافات': Icons.local_laundry_service_rounded,
      'غسيل ملابس': Icons.local_laundry_service_rounded,
      'مكانس كهربائية': Icons.cleaning_services_rounded,

      // سيارات
      'اطارات وجنوط': Icons.tire_repair_rounded,
      'بطاريات سيارات': Icons.battery_charging_full_rounded,
      'اكسسوارات داخلية': Icons.car_repair_rounded,
      'مواطير وبطاريات': Icons.battery_full_rounded,

      // حديقة
      'أدوات زراعة': Icons.yard_rounded,
      'بذور وأسمدة': Icons.grass_rounded,
      'شجر ونباتات': Icons.park_rounded,
      'ورد صناعي': Icons.local_florist_rounded,
      'ورد طبيعي': Icons.local_florist_rounded,
      'باقات ورد': Icons.local_florist_rounded,
      'شبكات ري': Icons.water_rounded,
      'بيوت محمية': Icons.home_rounded,
      'مضلات وبرجولات': Icons.umbrella_rounded,
      'سياج وتغطية': Icons.fence_rounded,

      // رحلات وسفر
      'خيام وسواتر': Icons.cabin_rounded,
      'خيمة وبيوت': Icons.cabin_rounded,
      'طاولات رحلات': Icons.table_bar_rounded,
      'كراسي رحلات': Icons.chair_rounded,
      'إنارة رحلات': Icons.flashlight_on_rounded,
      'عزبة الرحلات': Icons.terrain_rounded,
      'مضلات مطر': Icons.umbrella_rounded,
      'حقائب سفر': Icons.luggage_rounded,
      'وسائد سفر': Icons.airline_seat_recline_normal_rounded,
      'موازين حقائب': Icons.scale_rounded,
      'اكسسوارات سفر': Icons.travel_explore_rounded,
      'خدمات الفندقة': Icons.hotel_rounded,

      // حيوانات
      'القطط ومسلتزماتها': Icons.pets_rounded,
      'الطيور ومسلتزماتها': Icons.flutter_dash,
      'الأسماك ومسلتزماتها': Icons.set_meal_rounded,
      'الزواحف ومسلتزماتها': Icons.pest_control_rounded,
      'الخيول ومسلتزماتها': Icons.sports_rounded,
      'القوارض ومسلتزماتها': Icons.pest_control_rodent_rounded,
      'المواشي ومسلتزماتها': Icons.agriculture_rounded,
      'ملابس الحيوانات': Icons.checkroom_rounded,
      'مكملات الحيوانات': Icons.medication_rounded,

      // كتب وقرطاسية
      'روايات وقصص': Icons.auto_stories_rounded,
      'كتب أطفال': Icons.menu_book_rounded,
      'كتب تاريخية': Icons.history_edu_rounded,
      'كتب تعليمية': Icons.school_rounded,
      'كتب دينية': Icons.mosque_rounded,
      'كتب عامة': Icons.menu_book_rounded,
      'كتب علمية': Icons.science_rounded,
      'كتب نادرة': Icons.auto_stories_rounded,
      'قصص وكتب': Icons.menu_book_rounded,
      'أقلام واحبار': Icons.edit_rounded,
      'دفاتر ونوتات': Icons.note_rounded,
      'أوراق طباعة': Icons.description_rounded,
      'أدوات مدرسية': Icons.school_rounded,
      'مستلزمات مدرسية': Icons.school_rounded,
      'أدوات تعليمية': Icons.school_rounded,
      'سبورات ووسائل': Icons.dashboard_rounded,
      'اكسسوارات كتب': Icons.bookmark_rounded,
      'مستلزمات مكتبية': Icons.business_center_rounded,
      'حقائب مدرسية': Icons.backpack_rounded,

      // هدايا
      'أكياس هدايا': Icons.card_giftcard_rounded,
      'صناديق هدايا': Icons.redeem_rounded,
      'توزيعات زواج': Icons.favorite_rounded,
      'توزيعات مواليد': Icons.child_friendly_rounded,
      'توزيعات العيد': Icons.celebration_rounded,
      'توزيعات عامة': Icons.redeem_rounded,
      'طباعة هدايا': Icons.print_rounded,
      'هدايا مواليد': Icons.child_friendly_rounded,

      // عالم الطفل
      'عربات مواليد': Icons.child_friendly_rounded,
      'أسرة مواليد': Icons.crib_rounded,
      'شنط مواليد': Icons.backpack_rounded,
      'أدوات رضاعة': Icons.baby_changing_station_rounded,
      'ملابس مواليد': Icons.checkroom_rounded,
      'أحذية مواليد': Icons.checkroom_rounded,
      'مفارش مواليد': Icons.bed_rounded,
      'عناية واستحمام مواليد': Icons.shower_rounded,
      'هزازي وكراسي': Icons.chair_rounded,
      'تجهيزات حضانة': Icons.crib_rounded,
      'كراسي سيارة': Icons.child_friendly_rounded,
      'فيتامينات أطفال': Icons.medication_rounded,

      // مواليد
      'ملابس تنكرية': Icons.checkroom_rounded,

      // مكملات غذائية
      'بروتينات': Icons.fitness_center_rounded,
      'أحماض أمينية': Icons.science_rounded,
      'أوميجا وزيوت': Icons.water_drop_rounded,
      'فيتامينات ومعادن': Icons.medication_rounded,
      'كرياتين وطاقة': Icons.bolt_rounded,
      'مكملات طبيعية': Icons.eco_rounded,
      'مكملات كيتو': Icons.restaurant_menu_rounded,

      // عروض طبية
      'أجهزة ضغط': Icons.monitor_heart_rounded,
      'أجهزة سكري': Icons.bloodtype_rounded,
      'أجهزة تنفس': Icons.air_rounded,
      'أجهزة حرارة': Icons.thermostat_rounded,
      'نظارات طبية': Icons.visibility_rounded,
      'عكازات ومشايات': Icons.accessible_rounded,
      'كراسي متحركة': Icons.accessible_rounded,
      'مشدات طبية': Icons.health_and_safety_rounded,
      'مراكن وأحواض': Icons.bathtub_rounded,
      'مستلزمات حمام': Icons.bathtub_rounded,

      // منظفات
      'منظفات أرضيات': Icons.cleaning_services_rounded,
      'منظفات أفران': Icons.cleaning_services_rounded,
      'منظفات المكائن': Icons.cleaning_services_rounded,
      'منظفات زجاج': Icons.window_rounded,
      'أدوات تنظيف': Icons.cleaning_services_rounded,
      'مطهرات ومعقمات': Icons.sanitizer_rounded,
      'مزيلات بقع': Icons.cleaning_services_rounded,
      'منعمات اقمشة': Icons.local_laundry_service_rounded,
      'مناديل ورقية': Icons.receipt_rounded,
      'أكياس نفايات': Icons.delete_rounded,
      'ملمعات اسطح': Icons.cleaning_services_rounded,
      'مبيدات حشرية': Icons.pest_control_rounded,

      // حرف يدوية
      'أدوات رسم': Icons.draw_rounded,
      'أدوات خياطه': Icons.content_cut_rounded,
      'أدوات الخط': Icons.edit_rounded,
      'أدوات صلصال': Icons.architecture_rounded,
      'أعمال كروشية': Icons.texture_rounded,
      'خيوط وتطريز': Icons.texture_rounded,
      'صناعة الصابون': Icons.soap_rounded,
      'صناعة شموع': Icons.light_mode_rounded,
      'قوالب ريزن': Icons.science_rounded,
      'أقمشة ومنسوجات': Icons.texture_rounded,
      'جلود طبيعية': Icons.texture_rounded,
      'أدوات نجارة': Icons.handyman_rounded,
      'أدوات هندسية': Icons.engineering_rounded,
      'ادوات سحب': Icons.handyman_rounded,

      // محافظ وحقائب
      'أرواج': Icons.water_drop_rounded,
      'ثياب وأقمشة': Icons.checkroom_rounded,
      'جلد طبيعي': Icons.texture_rounded,
    };

    return subIconMap[subName] ?? getIcon(parentName);
  }
}
